// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin-api/current-user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the user resolved from the JWT identity (` + "`" + `id` + "`" + `) in the request context.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Get current authenticated admin user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_domain_entity.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/dashboard": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a simple dashboard welcome message for authenticated admin users.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-dashboard"
                ],
                "summary": "Get admin dashboard greeting",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.DashboardResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.AuthErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.AuthErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/reports/visits": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns paginated visitor attendance information aggregated per visitor per day for a given date range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-reports"
                ],
                "summary": "Get visitor attendance report",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, inclusive)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, inclusive)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by student flag",
                        "name": "is_student",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by year group",
                        "name": "year_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by sign status (not_signed, signed_in, signed_out)",
                        "name": "sign_status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Records per page (default 100, max 1000)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ReportsVisitsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a paginated, field-selectable visitor attendance report with multi-value filters and server-side sorting.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-reports"
                ],
                "summary": "Search visitor attendance report",
                "parameters": [
                    {
                        "description": "Search criteria",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.PostReportsVisitsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.PostReportsVisitsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/theme": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns current tracking page theme assets and timing settings.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-theme"
                ],
                "summary": "Get current theme",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_usecase_theme.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/theme/assets/{slot}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Uploads a custom asset for the given theme slot.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-theme"
                ],
                "summary": "Upload theme asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Theme slot",
                        "name": "slot",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Theme asset file",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_usecase_theme.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Removes a custom asset assignment and restores the default slot asset.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-theme"
                ],
                "summary": "Reset theme asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Theme slot",
                        "name": "slot",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_usecase_theme.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/theme/settings": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Updates welcome and goodbye animation durations for the tracking page.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-theme"
                ],
                "summary": "Update theme settings",
                "parameters": [
                    {
                        "description": "Theme settings request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.UpdateThemeSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_usecase_theme.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/track/visit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Manually records a visitor sign-in/sign-out event on behalf of a visitor by an admin.\nUsed when a visitor forgot their key, lost it, or is otherwise unable to use it.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-tracking"
                ],
                "summary": "Manual visitor track",
                "parameters": [
                    {
                        "description": "Track request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ManualTrackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ManualTrackResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns all users available in the administration area.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "List admin users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_buzyka_imlate_internal_domain_entity.User"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a new user account for the admin panel.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Create admin user",
                "parameters": [
                    {
                        "description": "Create user request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_domain_entity.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/users/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns one user by UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_domain_entity.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Updates profile and role fields for the user identified by UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Update admin user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update user request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_domain_entity.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes the user identified by UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Delete admin user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/users/{id}/password": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Replaces the password of the user identified by UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Update user password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update password request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.UpdatePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/version": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the current application version. In development returns \"2.0.x-dev\", in production the actual release version.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-system"
                ],
                "summary": "Get application version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.VersionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.AuthErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.AuthErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/visitors": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns all visitors available in the administration area.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-visitors"
                ],
                "summary": "List visitors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_http_controller_adminapi.VisitorResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a visitor record with optional keys and student metadata.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-visitors"
                ],
                "summary": "Create visitor",
                "parameters": [
                    {
                        "description": "Create visitor request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.CreateVisitorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.VisitorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/visitors/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns one visitor by numeric identifier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-visitors"
                ],
                "summary": "Get visitor by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Visitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.VisitorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Updates visitor profile data, including keys and student fields.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-visitors"
                ],
                "summary": "Update visitor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Visitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update visitor request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.UpdateVisitorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.VisitorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes the visitor identified by numeric ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-visitors"
                ],
                "summary": "Delete visitor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Visitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/visitors/{id}/image": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Uploads an image file for the specified visitor.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-visitors"
                ],
                "summary": "Upload visitor image",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Visitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Visitor image file",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.VisitorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/visitors/{id}/key": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Adds one access key to the specified visitor.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-visitors"
                ],
                "summary": "Add visitor key",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Visitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add key request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.AddKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin-api/visitors/{id}/key/{key}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Removes one access key from the specified visitor.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-visitors"
                ],
                "summary": "Remove visitor key",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Visitor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Visitor key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticates a user with username/password and returns a JWT token.\nCredentials can be sent as JSON or form fields (` + "`" + `username` + "`" + `, ` + "`" + `password` + "`" + `).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login for admin API",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.AuthTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.AuthErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.AuthErrorResponse"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "description": "Refreshes a valid JWT token and returns a new token pair.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh admin JWT token",
                "parameters": [
                    {
                        "description": "Refresh token payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.AuthTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.AuthErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_http_controller_adminapi.AuthErrorResponse"
                        }
                    }
                }
            }
        },
        "/register-terminal": {
            "post": {
                "description": "Validates admin credentials and creates (or force-updates) a terminal user.\nReturns the generated password as ` + "`" + `auth_token` + "`" + `. This token is only returned\nat creation or regeneration time and should be stored securely by the client.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminal"
                ],
                "summary": "Register a terminal",
                "parameters": [
                    {
                        "description": "Terminal registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.RegisterTerminalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.RegisterTerminalResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Terminal with this name already exists",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_adminapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/theme-state": {
            "get": {
                "description": "Returns the current tracking page theme together with a revision fingerprint.\nThe tracking page polls this endpoint and refreshes its appearance only when the\nrevision differs from the one it was rendered with, so an admin's theme change\nreaches long-running terminals without anyone reloading them by hand.\nPublic by design: the payload is exactly what the public tracking page already\nrenders, and terminals must be able to poll it before they are registered.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reader"
                ],
                "summary": "Get tracking page theme state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_buzyka_imlate_internal_usecase_theme.ReaderPageData"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_reader.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_buzyka_imlate_internal_domain_entity.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/github_com_buzyka_imlate_internal_domain_entity.UserRole"
                },
                "surname": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_buzyka_imlate_internal_domain_entity.UserRole": {
            "type": "string",
            "enum": [
                "admin",
                "terminal"
            ],
            "x-enum-varnames": [
                "UserRoleAdmin",
                "UserRoleTerminal"
            ]
        },
        "github_com_buzyka_imlate_internal_domain_entity.Visitor": {
            "type": "object",
            "properties": {
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "grade": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "is_student": {
                    "type": "boolean"
                },
                "isams_divisions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "isams_id": {
                    "type": "integer"
                },
                "isams_school_id": {
                    "type": "string"
                },
                "isams_year_group_id": {
                    "type": "integer"
                },
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_buzyka_imlate_internal_http_controller_adminapi.AuthErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_buzyka_imlate_internal_http_controller_adminapi.AuthTokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "github_com_buzyka_imlate_internal_http_controller_adminapi.DashboardResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_buzyka_imlate_internal_http_controller_adminapi.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_buzyka_imlate_internal_http_controller_adminapi.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_buzyka_imlate_internal_http_controller_adminapi.VersionResponse": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string"
                }
            }
        },
        "github_com_buzyka_imlate_internal_usecase_adminapi.PostReportsVisitsFilters": {
            "type": "object",
            "properties": {
                "is_student": {
                    "type": "boolean"
                },
                "sign_status": {
                    "description": "SignStatus filters rows by sign status. Allowed values: signed_in, signed_out, not_signed.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "year_group": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_buzyka_imlate_internal_usecase_adminapi.PostReportsVisitsOrder": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string",
                    "enum": [
                        "asc",
                        "desc"
                    ]
                },
                "field": {
                    "type": "string",
                    "enum": [
                        "sign_status",
                        "year_group",
                        "name",
                        "surname",
                        "visit_date",
                        "visits_count"
                    ]
                }
            }
        },
        "github_com_buzyka_imlate_internal_usecase_adminapi.ReportsVisitsResponseItem": {
            "type": "object",
            "properties": {
                "duration_minutes": {
                    "type": "integer"
                },
                "is_student": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "sign_status": {
                    "type": "string"
                },
                "signed_in": {
                    "type": "string"
                },
                "signed_out": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                },
                "visit_date": {
                    "type": "string"
                },
                "visitor_id": {
                    "type": "integer"
                },
                "visits_count": {
                    "type": "integer"
                },
                "year_group": {
                    "type": "integer"
                }
            }
        },
        "github_com_buzyka_imlate_internal_usecase_theme.AssetState": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "current_url": {
                    "type": "string"
                },
                "default_url": {
                    "type": "string"
                },
                "is_custom": {
                    "type": "boolean"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "slot": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_buzyka_imlate_internal_usecase_theme.ReaderPageData": {
            "type": "object",
            "properties": {
                "app_version": {
                    "description": "AppVersion lets the page tell a theme change from a deploy: on a new\nversion the template itself may have changed, which an in-place theme\nupdate cannot pick up, so the page reloads instead.",
                    "type": "string"
                },
                "favicon_url": {
                    "type": "string"
                },
                "goodbye_animation_url": {
                    "type": "string"
                },
                "goodbye_duration_ms": {
                    "type": "integer"
                },
                "logo_background_url": {
                    "type": "string"
                },
                "poll_seconds": {
                    "description": "PollSeconds is how often the page should poll for changes.",
                    "type": "integer"
                },
                "revision": {
                    "description": "Revision fingerprints the six fields above, so it changes if and only if\nsomething the page actually renders changed. The page compares the value\nbaked into it at render time against the one the endpoint reports and only\nrefreshes its theme when they differ.",
                    "type": "string"
                },
                "welcome_animation_url": {
                    "type": "string"
                },
                "welcome_duration_ms": {
                    "type": "integer"
                }
            }
        },
        "github_com_buzyka_imlate_internal_usecase_theme.Response": {
            "type": "object",
            "properties": {
                "assets": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_buzyka_imlate_internal_usecase_theme.AssetState"
                    }
                },
                "settings": {
                    "$ref": "#/definitions/github_com_buzyka_imlate_internal_usecase_theme.Settings"
                }
            }
        },
        "github_com_buzyka_imlate_internal_usecase_theme.Settings": {
            "type": "object",
            "properties": {
                "goodbye_duration_ms": {
                    "type": "integer"
                },
                "welcome_duration_ms": {
                    "type": "integer"
                }
            }
        },
        "internal_http_controller_adminapi.AddKeyRequest": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "key": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_adminapi.CreateUserRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "role",
                "surname",
                "username"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/github_com_buzyka_imlate_internal_domain_entity.UserRole"
                },
                "surname": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_adminapi.CreateVisitorRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "grade": {
                    "type": "integer"
                },
                "is_student": {
                    "type": "boolean"
                },
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_adminapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_adminapi.ManualTrackRequest": {
            "type": "object",
            "required": [
                "visitor_id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "signed_in": {
                    "type": "boolean"
                },
                "visitor_id": {
                    "type": "integer"
                }
            }
        },
        "internal_http_controller_adminapi.ManualTrackResponse": {
            "type": "object",
            "properties": {
                "track_date": {
                    "type": "string"
                },
                "track_type": {
                    "type": "string"
                },
                "visitor": {
                    "$ref": "#/definitions/github_com_buzyka_imlate_internal_domain_entity.Visitor"
                }
            }
        },
        "internal_http_controller_adminapi.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_adminapi.PostReportsVisitsRequest": {
            "type": "object",
            "properties": {
                "fields": {
                    "description": "Fields selects which optional fields to include in each row.\nComputed fields (visit_date, sign_status, visits_count, signed_in, signed_out, duration_minutes)\nare always present regardless of this list.\nAllowed values: visitor_id, visit_date, name, surname, is_student, year_group,\nvisits_count, sign_status, signed_in, signed_out, duration_minutes, email, image.\nOmit or leave empty to return all optional fields.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "filters": {
                    "$ref": "#/definitions/github_com_buzyka_imlate_internal_usecase_adminapi.PostReportsVisitsFilters"
                },
                "from": {
                    "type": "string"
                },
                "limit": {
                    "description": "Limit is the page size. Defaults to 100 when omitted; must not exceed 1000.",
                    "type": "integer",
                    "maximum": 1000
                },
                "order": {
                    "$ref": "#/definitions/github_com_buzyka_imlate_internal_usecase_adminapi.PostReportsVisitsOrder"
                },
                "page": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_adminapi.PostReportsVisitsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "internal_http_controller_adminapi.RegisterTerminalRequest": {
            "type": "object",
            "required": [
                "admin_login",
                "admin_password",
                "terminal_name"
            ],
            "properties": {
                "admin_login": {
                    "type": "string"
                },
                "admin_password": {
                    "type": "string"
                },
                "force_update": {
                    "type": "boolean"
                },
                "terminal_name": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_adminapi.RegisterTerminalResponse": {
            "type": "object",
            "properties": {
                "auth_token": {
                    "type": "string"
                },
                "terminal_name": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_adminapi.ReportsVisitsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_buzyka_imlate_internal_usecase_adminapi.ReportsVisitsResponseItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "internal_http_controller_adminapi.UpdatePasswordRequest": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "internal_http_controller_adminapi.UpdateThemeSettingsRequest": {
            "type": "object",
            "required": [
                "goodbye_duration_ms",
                "welcome_duration_ms"
            ],
            "properties": {
                "goodbye_duration_ms": {
                    "type": "integer"
                },
                "welcome_duration_ms": {
                    "type": "integer"
                }
            }
        },
        "internal_http_controller_adminapi.UpdateUserRequest": {
            "type": "object",
            "required": [
                "name",
                "role",
                "surname"
            ],
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/github_com_buzyka_imlate_internal_domain_entity.UserRole"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_adminapi.UpdateVisitorRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "grade": {
                    "type": "integer"
                },
                "is_student": {
                    "type": "boolean"
                },
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_adminapi.VisitorResponse": {
            "type": "object",
            "properties": {
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "grade": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "imported_from_isams": {
                    "type": "boolean"
                },
                "is_student": {
                    "type": "boolean"
                },
                "isams_divisions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "isams_id": {
                    "type": "integer"
                },
                "isams_school_id": {
                    "type": "string"
                },
                "isams_year_group_id": {
                    "type": "integer"
                },
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_reader.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "JWT token in format: \"Bearer \u003cJWT\u003e\".\nToken lookup order: Authorization header, query parameter ` + "`" + `token` + "`" + `, cookie ` + "`" + `jwt` + "`" + `.\nProtected admin routes require admin role.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ImLate Admin API",
	Description:      "This is the administration API for the ImLate tracking system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
